//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculaterWebApplication.CalculatorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://ujjwal.com/webservices", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ujjwal.com/webservices", ConfigurationName="CalculatorService.CalculatorWebServiceSoap")]
    public interface CalculatorWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ujjwal.com/webservices/Add", ReplyAction="*")]
        int Add(int firstNumber, int secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ujjwal.com/webservices/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int firstNumber, int secondNumber);
        
        // CODEGEN: Generating message contract since element name GetCalculationResult from namespace http://ujjwal.com/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ujjwal.com/webservices/GetCalculation", ReplyAction="*")]
        CalculaterWebApplication.CalculatorService.GetCalculationResponse GetCalculation(CalculaterWebApplication.CalculatorService.GetCalculationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ujjwal.com/webservices/GetCalculation", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculaterWebApplication.CalculatorService.GetCalculationResponse> GetCalculationAsync(CalculaterWebApplication.CalculatorService.GetCalculationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculation", Namespace="http://ujjwal.com/webservices", Order=0)]
        public CalculaterWebApplication.CalculatorService.GetCalculationRequestBody Body;
        
        public GetCalculationRequest() {
        }
        
        public GetCalculationRequest(CalculaterWebApplication.CalculatorService.GetCalculationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCalculationRequestBody {
        
        public GetCalculationRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculationResponse", Namespace="http://ujjwal.com/webservices", Order=0)]
        public CalculaterWebApplication.CalculatorService.GetCalculationResponseBody Body;
        
        public GetCalculationResponse() {
        }
        
        public GetCalculationResponse(CalculaterWebApplication.CalculatorService.GetCalculationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ujjwal.com/webservices")]
    public partial class GetCalculationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CalculaterWebApplication.CalculatorService.ArrayOfString GetCalculationResult;
        
        public GetCalculationResponseBody() {
        }
        
        public GetCalculationResponseBody(CalculaterWebApplication.CalculatorService.ArrayOfString GetCalculationResult) {
            this.GetCalculationResult = GetCalculationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorWebServiceSoapChannel : CalculaterWebApplication.CalculatorService.CalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<CalculaterWebApplication.CalculatorService.CalculatorWebServiceSoap>, CalculaterWebApplication.CalculatorService.CalculatorWebServiceSoap {
        
        public CalculatorWebServiceSoapClient() {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int firstNumber, int secondNumber) {
            return base.Channel.Add(firstNumber, secondNumber);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int firstNumber, int secondNumber) {
            return base.Channel.AddAsync(firstNumber, secondNumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculaterWebApplication.CalculatorService.GetCalculationResponse CalculaterWebApplication.CalculatorService.CalculatorWebServiceSoap.GetCalculation(CalculaterWebApplication.CalculatorService.GetCalculationRequest request) {
            return base.Channel.GetCalculation(request);
        }
        
        public CalculaterWebApplication.CalculatorService.ArrayOfString GetCalculation() {
            CalculaterWebApplication.CalculatorService.GetCalculationRequest inValue = new CalculaterWebApplication.CalculatorService.GetCalculationRequest();
            inValue.Body = new CalculaterWebApplication.CalculatorService.GetCalculationRequestBody();
            CalculaterWebApplication.CalculatorService.GetCalculationResponse retVal = ((CalculaterWebApplication.CalculatorService.CalculatorWebServiceSoap)(this)).GetCalculation(inValue);
            return retVal.Body.GetCalculationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculaterWebApplication.CalculatorService.GetCalculationResponse> CalculaterWebApplication.CalculatorService.CalculatorWebServiceSoap.GetCalculationAsync(CalculaterWebApplication.CalculatorService.GetCalculationRequest request) {
            return base.Channel.GetCalculationAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculaterWebApplication.CalculatorService.GetCalculationResponse> GetCalculationAsync() {
            CalculaterWebApplication.CalculatorService.GetCalculationRequest inValue = new CalculaterWebApplication.CalculatorService.GetCalculationRequest();
            inValue.Body = new CalculaterWebApplication.CalculatorService.GetCalculationRequestBody();
            return ((CalculaterWebApplication.CalculatorService.CalculatorWebServiceSoap)(this)).GetCalculationAsync(inValue);
        }
    }
}
